api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('books/', views.BookListAPIView.as_view(), name='books'),
    path('posts/', views.PostAPIView.as_view(), name='posts'),
    path('profile/', views.get_profile, name='profile'),
    path('my-profile/', views.my_profile, name='my-profile'),
    path('create-post/', views.PostCreateAPIView.as_view(), name='create-post'),
    path('borrowing/', views.BorrowingAPIView.as_view(), name='borrowing'),
    path('recommendations/', views.RecommendationAPIView.as_view(), name='recommendations'),
    path('announcements/', views.AnnouncementAPIView.as_view(), name='announcements'),
    path('app-link/', views.app_link, name='app-link'),
    path('subcategories/', views.SubcategoryAPIView.as_view(), name='subcategories')
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    #path('borrow/create-borrower/', views.BorrowerCreateView.as_view(), name='create-borrower'),
    path('borrow/create-borrowing/', views.create_borrowing, name='create-borrowing'),
    path('borrow/return-book/', views.return_book, name='return-book'),
    path('books/create-book/', views.BookCreateView.as_view(), name='create-book'),
    path('books/edit-book/', views.edit_book, name='edit-book'),
    path('books/edit-book/<int:pk>/', views.edit_book_details, name='edit-book-details'),
    path('email-to-instatech/', views.send_email_to_instatech, name='email-to-instatech'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('', include('my_auth.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('dj_rest_auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_auth/urls.py
from django.urls import path
from . import views

app_name = 'my-auth'

urlpatterns = [
    path('web-auth/login/', views.mylogin, name='login'),
    path('web-auth/logout/', views.mylogout, name='logout'),
    path('web-auth/create-profile/', views.create_profile, name='create-profile'),
    path('my-account/', views.my_account, name='my-account'),
    path('my-account/change-password/', views.CustomPasswordChangeView.as_view(), name='change-password'),
    path('my-account/change-photo/', views.PorfilePhotoChangeView.as_view(), name='change-photo'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('recent/', views.PostListView.as_view(), name='posts'),
    path('search/', views.search_posts, name='search'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='details'),
    path('profile/<int:pk>/', views.posts_by_profile, name='profile-posts'),
    path('create/', views.create_post, name='create-post'),
]

my_auth/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

from books.models import Book

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='الحساب')
    photo = models.ImageField(blank=True, null=True, upload_to='profile_photos', verbose_name='الصورة')
    books = models.ManyToManyField(Book, blank=True, verbose_name='الكتب التي استعارها')

    def __str__(self):
        return self.name
    
    @property
    def name(self):
        return self.user.first_name + ' ' + self.user.last_name

    @property
    def count_books(self):
        return self.books.count() 

class Post(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='الكاتب')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True, verbose_name='الكتاب')
    title = models.CharField(max_length=255, verbose_name='العنوان')
    text = models.TextField(max_length=50000, verbose_name='النص')
    image = models.URLField(blank=True, verbose_name='الصورة')
    approved = models.BooleanField(default=False, verbose_name='قبول المشاركة')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')

    def __str__(self):
        return self.title + ' للكاتب: ' + self.profile.name

my_auth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm, AuthenticationForm
from posts.models import Profile

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'اسم المستخدم'
        self.fields['password'].label = 'كلمة المرور'

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'email')
        widgets = {
            'password': forms.PasswordInput(),
        }

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = 'كلمة السر القديمة'
        self.fields['new_password1'].label = 'كلمة السر الجديدة'
        self.fields['new_password2'].label = 'أعد كتابة كلمة السر الجديدة'
        self.fields['new_password1'].help_text = 'كلمة السر الجديدة يجب ان تتكون من 8 رموز ولا تحتوي على اسم المستخدم ولا تتشابه مع كلمة السر القديمة*'

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('books', 'user')

my_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.views import PasswordChangeView
from django.views import generic
from .forms import ProfileForm, UserProfileForm, CustomPasswordChangeForm, CustomAuthenticationForm
from books.models import Borrowing


# Create your views here.
def mylogin(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('my-auth:my-account')
            else:
                error = True
                return render(request, 'my_auth/login.html', {'form': form, 'error': error})
        else:
            error = True
            return render(request, 'my_auth/login.html', {'form': form, 'error': error})
    error = False
    form = CustomAuthenticationForm()
    return render(request, 'my_auth/login.html', {'form': form, 'error': error})

def mylogout(request):
    logout(request)
    return redirect('books:index')

@login_required(login_url='/admin/login/')
@staff_member_required
def create_profile(request):
    if request.method == 'POST':
        user_form = UserProfileForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            return render(request, 'my_auth/create_profile.html', {'user_form': user_form, 'profile_form': profile_form, 'success': True})
        else: 
           return render(request, 'my_auth/create_profile.html', {'user_form': user_form, 'profile_form': profile_form, 'error': True})
         
    else:
        user_form = UserProfileForm()
        profile_form = ProfileForm()
        return render(request, 'my_auth/create_profile.html', {'user_form': user_form, 'profile_form': profile_form,})

@login_required(login_url='/web-auth/login')
def my_account(request):
    borrowings = Borrowing.objects.filter(borrower=request.user.profile).prefetch_related()
    return render(request, 'my_auth/my_account.html', {'borrowings': borrowings})

class CustomPasswordChangeView(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'my_auth/change_password.html'
    success_url = '/web-auth/my-account/change-password/'

class PorfilePhotoChangeView(generic.UpdateView):
    form_class = ProfileForm
    template_name = 'my_auth/change_photo.html'
    success_url = '/web-auth/my-account/change-photo/'

    def get_object(self, queryset=None):
        queryset = self.request.user.profile
        return queryset
    
    def form_valid(self, form):
        response = super().form_valid(form)
        photo_clear = self.request.POST.get('photo-clear', False)
        
        if photo_clear:
            self.object.photo.delete()
            self.object.photo = None
            self.object.save()

        if 'photo' in self.request.FILES:
            self.object.photo = self.request.FILES['photo']
            self.object.save()

        return response
        

my_auth/templates/my_auth/change_password.html
{% extends 'my_auth/my_account.html' %}

{% block active_button %}
<div class="container">
    <div class="row gtr-150">
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button acitve" href="{% url 'my-auth:my-account' %}">حسابي</a>
        </div>
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button active" href="{% url 'my-auth:change-password' %}">تغيير كلمة المرور</a>
        </div>
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'my-auth:change-photo' %}">تغيير الصورة الشخصية</a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container" style="margin: auto;">
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="حفظ">
    </form>
</div>
{% endblock %}

my_auth/templates/my_auth/change_photo.html
{% extends 'my_auth/my_account.html' %}

{% block active_button %}
<div class="container">
    <div class="row gtr-150">
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'my-auth:my-account' %}">حسابي</a>
        </div>
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'my-auth:change-password' %}">تغيير كلمة المرور</a>
        </div>
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button active" href="{% url 'my-auth:change-photo' %}">تغيير الصورة الشخصية</a>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container" style="margin: auto;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <label for="id_photo">الصورة:</label>
            الصورة الحالية: 
            {% if object.photo %}
            <a href="{{ object.photo.url }}">{{ object.photo }}</a>
            <input type="checkbox" name="photo-clear" id="photo-clear_id">
            <label for="photo-clear_id">مسح</label>
            {% else %}
            لا يوجد. 
            {% endif %}
            <br>
            تغيير:
            <input type="file" name="photo" accept="image/*" id="id_photo">
        </p>
        <input type="submit" value="حفظ">
    </form>
</div>
{% endblock %}

my_auth/templates/my_auth/create_profile.html
{% extends "books/borrowing_form.html" %}

{% block search %}
<div class="container">
    <div class="row gtr-150">
        <div class="col-4 col-12-medium" style="display: flex; justify-content: center;">
            <a class="button active" href="{% url 'my-auth:create-profile' %}">إضافة عضو جديد</a>
        </div>
        <div class="col-4 col-12-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'books:create-borrowing' %}">إضافة طلب استعارة جديد</a>
        </div>
        <div class="col-4 col-12-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'books:return-book' %}">إرجاع كتاب</a>
        </div>
    </div>
</div>
<br />
{% block content %}
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col">
            {% if success %}
            <h2 style="color:green;">تم تسجيل العضو بنجاح</h2>
            {% endif %}
            {% if error %}
            <h2 style="color:red;">يوجد خطأ في البيانات</h2>
            {% endif %}

            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ user_form.as_p }}
                <br>
                {{ profile_form.as_p }}
                <input type="submit" value="حفظ">
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% endblock %}

my_auth/templates/my_auth/login.html
{% extends "books/search.html" %}

{% block active %}
<li><a class="anav" href="{% url 'books:index' %}">الرئيسية</a></li>
<li><a class="anav" href="{% url 'books:search' %}">البحث</a></li>
<li><a class="anav" href="{% url 'posts:posts' %}">المشاركات</a></li>
{% if user.is_staff %}
<li><a class="anav" href="{% url 'books:create-borrowing' %}">الاستعارة</a></li>
<li><a class="anav" href="{% url 'books:create-book' %}">الكتب</a></li>
{% endif %}
{% endblock %}

{% block search %}
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        {% block form %}
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            {% if error %}
            <h2 style="color:red;">اسم المستخدم او كلمة المرور غير صحيحة.</h2>
            {% endif %}
            <input type="submit" value="تسجيل الدخول">
        </form>
        {% endblock %}
    </div>
</div>
{% endblock %}

my_auth/templates/my_auth/my_account.html
{% extends 'books/search.html' %}
{% block stylesheets %}
{% endblock %}

{% block header %}
{% endblock %}

{% block search %}
<div class="container">
    <div class="row" style="display: flex; justify-content: center; align-items: center;">
        <div class="col-6" style="display: flex; justify-content: center;">
            <img src="/media/{{ request.user.profile.photo }}" width="250" height="250" style="border-radius: 50%;">
        </div>
    </div>
    <div class="row " style="display: flex; align-items: center;">
        <div class="col-6 col-6-medium" style="display: flex; justify-content: center;">
            <h2>معلومات الحساب: </h2>
        </div>
    </div>
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-6 col-12-medium" style="display: flex; justify-content: center;">
            <h4>الاسم: {{ request.user.profile.name }}</h4>
        </div>
        <div class="col-6 col-12-medium" style="display: flex; justify-content: center;">
            <h4>البريد الإلكتروني: {{ request.user.email }}</h4>
        </div>
    </div>
</div>
<br>

{% block active_button %}
<div class="container">
    <div class="row gtr-150" style="display: flex; justify-content: center; align-items: center;">
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button active" href="{% url 'my-auth:my-account' %}">حسابي</a>
        </div>
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'my-auth:change-password' %}">تغيير كلمة المرور</a>
        </div>
        <div class="col-4 col-6-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'my-auth:change-photo' %}">تغيير الصورة الشخصية</a>
        </div>
    </div>
</div>
{% endblock %}

<br>
{% block content %}
{% if borrowings %}
<div class="container mt-5 px-2">
    <h2>الاستعارات: </h2>
	<div class="table-responsive">
		<table class="table table-responsive">
			<thead>
				<tr class="bg-light">
					<th scope="col" width="40%" style="text-align: center;">الاسم</th>
					<th scope="col" width="25%" style="text-align: center;">تاريخ الاستعارة</th>
					<th scope="col" width="25%" style="text-align: center;">تاريخ الإرجاع</th>
					<th scope="col" width="10%" style="text-align: center;">تم الإرجاع</th>
				</tr>
			</thead>
			<tbody>
				{% for borrowing in borrowings %}
				<tr>
					<td style="text-align: center;">{{ borrowing.book.name }}</td>
					<td style="text-align: center;">{{ borrowing.borrow_date|date:"d/m/Y" }}</td>
                    {% if borrowing.return_date %}
					<td style="text-align: center;">{{ borrowing.return_date|date:"d/m/Y" }}</td>
                    {% else %}
                    <td style="text-align: center;">غير محدد</td>
                    {% endif %}
					{% if borrowing.returned %}
					<td style="text-align: center;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="green" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
					  </svg></td>
					{% else %}
					<td style="text-align: center;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
					  </svg></td>
					{% endif %}
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endif %}
{% endblock %}
{% endblock %}

{% block active %}
<li><a class="anav" href="{% url 'books:index' %}">الرئيسية</a></li>
<li><a class="anav" href="{% url 'books:search' %}">البحث</a></li>
<li><a class="anav" href="{% url 'posts:posts' %}">المشاركات</a></li>
<li><a class="anav" href="{% url 'books:create-borrowing' %}">الاستعارة</a></li>
<li><a class="anav" href="{% url 'books:create-book' %}">الكتب</a></li>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block index-only %}
{% endblock %}