api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('books/', views.BookListAPIView.as_view(), name='books'),
    path('posts/', views.PostAPIView.as_view(), name='posts'),
    path('profile/', views.get_profile, name='profile'),
    path('my-profile/', views.my_profile, name='my-profile'),
    path('create-post/', views.PostCreateAPIView.as_view(), name='create-post'),
    path('borrowing/', views.BorrowingAPIView.as_view(), name='borrowing'),
    path('recommendations/', views.RecommendationAPIView.as_view(), name='recommendations'),
    path('announcements/', views.AnnouncementAPIView.as_view(), name='announcements'),
    path('app-link/', views.app_link, name='app-link'),
    path('subcategories/', views.SubcategoryAPIView.as_view(), name='subcategories')
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    #path('borrow/create-borrower/', views.BorrowerCreateView.as_view(), name='create-borrower'),
    path('borrow/create-borrowing/', views.create_borrowing, name='create-borrowing'),
    path('borrow/return-book/', views.return_book, name='return-book'),
    path('books/create-book/', views.BookCreateView.as_view(), name='create-book'),
    path('books/edit-book/', views.edit_book, name='edit-book'),
    path('books/edit-book/<int:pk>/', views.edit_book_details, name='edit-book-details'),
    path('email-to-instatech/', views.send_email_to_instatech, name='email-to-instatech'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('', include('my_auth.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('dj_rest_auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('recent/', views.PostListView.as_view(), name='posts'),
    path('search/', views.search_posts, name='search'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='details'),
    path('profile/<int:pk>/', views.posts_by_profile, name='profile-posts'),
    path('create/', views.create_post, name='create-post'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

from books.models import Book

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='الحساب')
    photo = models.ImageField(blank=True, null=True, upload_to='profile_photos', verbose_name='الصورة')
    books = models.ManyToManyField(Book, blank=True, verbose_name='الكتب التي استعارها')

    def __str__(self):
        return self.name
    
    @property
    def name(self):
        return self.user.first_name + ' ' + self.user.last_name

    @property
    def count_books(self):
        return self.books.count() 

class Post(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='الكاتب')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True, verbose_name='الكتاب')
    title = models.CharField(max_length=255, verbose_name='العنوان')
    text = models.TextField(max_length=50000, verbose_name='النص')
    image = models.URLField(blank=True, verbose_name='الصورة')
    approved = models.BooleanField(default=False, verbose_name='قبول المشاركة')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')

    def __str__(self):
        return self.title + ' للكاتب: ' + self.profile.name

posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'book', 'image']
        labels = {
            'image': _('رابط الصورة')
        }
        widgets = {
            'image': forms.widgets.URLInput
        }

posts/views.py
from typing import Any, Dict
from django.urls import reverse
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q, CharField, Value
from django.db.models.functions import Concat
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Post, Profile
from .forms import PostForm
# Create your views here.

class PostListView(ListView):
    model = Post
    paginate_by = 12
    ordering = '-timestamp'
    context_object_name = 'posts'

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(approved=True)

def search_posts(request):
    keyword = ''
    if request.method == 'POST':
        keyword = request.POST.get('search', '')
        posts = Post.objects.filter(approved=True).annotate(
            name=Concat(
                'profile__user__first_name',
                Value(' '),
                'profile__user__last_name',
                output_field=CharField())).filter(Q(title__icontains=keyword) | Q(text__icontains=keyword) | Q(name__icontains=keyword)).order_by('-timestamp')
        return render(request, 'posts/post_list.html', {'posts': posts, 'keyword': keyword})
    posts = Post.objects.filter(approved=True).order_by('-timestamp')[:12]
    return render(request, 'posts/post_list.html', {'posts': posts, 'keyword': keyword})

class PostDetailView(DetailView):
    model = Post
    template_name_suffix = '_detail'
    context_object_name = 'post'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.filter(approved=True).exclude(pk=self.get_object().pk).order_by('-timestamp')[:3]
        return context
    
def posts_by_profile(request, pk=1):
    profile = get_object_or_404(Profile, pk=pk)
    posts = Post.objects.filter(profile=profile, approved=True).order_by('-timestamp')
    return render(request, 'posts/post_list.html', {'posts': posts, 'keyword': profile.__str__})

'''
class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/admin/login/'
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'
    def get_success_url(self):
        return reverse('books:create-post',)
'''

@login_required(login_url='/web-auth/login/')
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            profile = request.user.profile
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            book = form.cleaned_data['book']
            image = form.cleaned_data['image']
            post = Post(title=title, text=text, profile=profile)
            if (book is not None) and (book != ''):
                post.book = book
            if (image is not None) and (image != ''):
                post.image = image
            post.save()
            return render(request, 'posts/post_form.html', {'form': form, 'success': True, 'error': False})
        else:
            return render(request, 'posts/post_form.html', {'form': form, 'error': True}, status=406) #Not acceptable
    form = PostForm()
    return render(request, 'posts/post_form.html', {'form': form})
    

posts/templates/posts/admin_change_list.html
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
    {{ block.super }}
    <li>
        <a href="?approved__exact=False" class="button" title="Filter by Unapproved">المشاركات الغير مقبولة</a>
    </li>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_list.html' %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.rtl.min.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="{% static 'css/post_style.css' %}">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}
{% block search %}

{% block content %}
<div class="container pb50">
    <div class="row">
        <div class="col-md-9 mb40">
            <article>
                {% if post.image %}
                <img src="{{ post.image }}" alt="" class="img-fluid mb30">
                {% else %}
                <img src="{% static 'images/logo1.png' %}" alt="" class="img-fluid mb30">
                {% endif %}
                <div class="post-content">
                    <h3>{{ post.title }}</h3>
                    <ul class="post-meta list-inline">
                        <li class="list-inline-item"  style="margin-left: 0px;">
                            <img src="/media/{{post.profile.photo}}" height="16px;" width="16px;" style="border-radius: 100%;"> 
                            <a href="{% url 'posts:profile-posts' post.profile.id %}">{{ post.profile.name }}</a>
                        </li>
                        <li class="list-inline-item">
                            <i class="fa fa-calendar-o"></i> <a href="{% url 'posts:details' post.id %}">{{ post.timestamp|date:'d-m-Y' }}</a>
                        </li>
                    </ul>
                    <br>
                    <p class="lead">{{ post.text | linebreaksbr }}</p>
                    </ul>
                </div>
            </article>
            <!-- post article-->

        </div>
        <div class="col-md-3 mb40">
            <div>
                <h4 class="sidebar-title">آخر المشاركات</h4>
                <ul class="list-unstyled">
                    {% for post in posts %}
                    <li class="media py-2 row">
                        <a href="{% url 'posts:details' post.id %}">
                            {% if post.image %}
                            <img class="d-flex mr-3 img-fluid" width="64" src="{{ post.image }}" alt="Generic placeholder image">
                            {% else %}
                            <img class="d-flex mr-3 img-fluid" width="64" src="{% static 'images/logo1.png' %}" alt="Generic placeholder image">
                            {% endif %}
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 mb-1"><a href="{% url 'posts:details' post.id %}">{{ post.title }}</a></h5> {{ post.timestamp|date:'d-m-Y' }}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% endblock %}

posts/templates/posts/post_form.html
{% extends 'books/search.html' %}
{% block stylesheets %}
{% endblock %}

{% block header %}
{% endblock %}

{% block search %}
<div class="container">
    <div class="row gtr-150">
        <div class="col-6 col-12-medium" style="display: flex; justify-content: center;">
            <a class="button" href="{% url 'posts:posts' %}">آخر المشاركات</a>
        </div>
        <div class="col-6 col-12-medium" style="display: flex; justify-content: center;">
            <a class="button active py-2" href="{% url 'posts:create-post' %}">إضافة مشاركة</a>
        </div>
    </div>
</div>
<br/>
{% block content %}
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        {% if success %}
            <h2 style="color:green;">تم حفظ المشاركة بنجاح. سيتم ظهورها فور اعتمادها.</h2>
        {% endif %}
        {% if error %}
            <h2 style="color:red;">يوجد مشكلة في بيانات المشاركة.</h2>
        {% endif %}
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="حفظ">
        </form>
    </div>
</div>
{% endblock %}
{% endblock %}

{% block active %}
<li><a class="anav" href="{% url 'books:index' %}">الرئيسية</a></li>
<li><a class="anav" href="{% url 'books:search' %}">البحث</a></li>
<li><a class="active anav" href="{% url 'posts:posts' %}">المشاركات</a></li>
{% if user.is_staff %}
<li><a class="anav" href="{% url 'books:create-borrowing' %}">الاستعارة</a></li>
<li><a class="anav" href="{% url 'books:create-book' %}">الكتب</a></li>
{% endif %}
{% endblock %}



{% block scripts %}
{% endblock %}

{% block index-only %}
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'books/search.html' %}
{% load post_extras %}
{% load static %}


{% block active %}
<li><a class="anav" href="{% url 'books:index' %}">الرئيسية</a></li>
<li><a class="anav" href="{% url 'books:search' %}">البحث</a></li>
<li><a class="active anav" href="{% url 'posts:posts' %}">المشاركات</a></li>
{% if user.is_staff %}
<li><a class="anav" href="{% url 'books:create-borrowing' %}">الاستعارة</a></li>
<li><a class="anav" href="{% url 'books:create-book' %}">الكتب</a></li>
{% endif %}
{% endblock %}


{% block search %}
<div class="container">
    <div class="row gtr-150">
        <div class="col-6 col-12-medium" style="display: flex; justify-content: center;">
            <a class="button active" href="{% url 'posts:posts' %}">آخر المشاركات</a>
        </div>
        <div class="col-6 col-12-medium" style="display: flex; justify-content: center; padding-top: 5px;">
            <a class="button" href="{% url 'posts:create-post' %}">إضافة مشاركة</a>
        </div>
    </div>
</div>
<br/>
<div class="container">
    <div class="row" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
        <form method="POST" action="{% url 'posts:search' %}">
            {% csrf_token %}
            <div
                style="display: flex; flex-direction: row; align-items: stretch;">
                {% block search_input %}
                <input type="text" placeholder="بحث.." name="search" value="{{ keyword }}"
                    style="margin-left: 5px;">
                {% endblock %}
                <button type="submit" style="display: inline; align-self: stretch; border-radius: 4px;"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
</div>
{% block content %}
<div class="container py-3">
    <div class="row" style="align-items: center; justify-content: center;">
        {% for post in posts %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 p-2" style="display: flex; justify-content: center;">
            <div class="card" style="width: 18rem; height: max-content; margin-top: 10px;">
                {% if post.image %}
                <a class="link" href="{% url 'posts:details' post.id %}"><img class="card-img-top" height="200px;" src="{{ post.image }}" alt="Card image cap"></a>
                {% else %}
                <a class="link" href="{% url 'posts:details' post.id %}"><img class="card-img-top" height="200px;" src="{% static 'images/logo1.png' %}" alt="Card image cap"></a>
                {% endif %}
                <div class="card-body">
                    <a class="link" href="{% url 'posts:details' post.id %}"><h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text" style="color: black;">{{ post.text | index }}...</p></a>
                    <a class="link" href="{% url 'posts:details' post.id %}" class="card-link">متابعة القراءة</a>
                    <hr />
                    <div class="text" styke="display:inline;">
                        <a class="link" href="{% url 'posts:profile-posts' post.profile.id %}"><h5 class="card-title" style="display: inline;">بقلم: {{ post.profile }}</h5> <i class="bi bi-patch-check-fill"></i></a>
                        <br>
                        <p style="display: inline; text-align: center;">بتاريخ: {{ post.timestamp | date:"d-m-Y" }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% endblock %}